version: '3'

services:
    mongodb:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

      ports:
        - 27017:27017
    mongoclient:
      image: mongoclient/mongoclient:latest
      depends_on:
        - mongodb
      links:
        - mongodb
    #   networks:
    #     - mongodb_net
      ports:
        - 3300:3000